{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
{{- /* k8s 1.21+ required */ -}}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: grafana
  labels:
    app: grafana
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: grafana
      release: {{ .Release.Name }}
