{{- if .Values.matomo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: matomo-mysqld-secret
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: mysqld-exporter
type: Opaque
data:
  prometheus.mysqld.data-source: {{ printf "%s:%s@(127.0.0.1:3306)/" .Values.matomo.db.username .Values.matomo.db.password | b64enc | quote }}
{{- end }}
