{{- if .Values.redirector.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirector
  labels:
    app: redirector
    component: nginx
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: redirector
      component: nginx
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/redirector/configmap.yaml") . | sha256sum }}
      labels:
        app: redirector
        component: nginx
        release: {{ .Release.Name }}
    spec:
      nodeSelector: {{ toJson .Values.redirector.nodeSelector }}
      volumes:
        - name: config
          configMap:
            name: redirector-config
      containers:
      - name: nginx
        image: nginx:1.13.6
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: config
{{- end }}
