{{- if .Values.redirector.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirector
  labels:
    app: redirector
  annotations:
    {{- range $key, $value := .Values.redirector.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $redirect := .Values.redirector.redirects }}
    - host: {{ $redirect.host.from | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redirector
                port:
                  number: 80
    {{- end }}
  tls:
    - secretName: {{ .Values.redirector.ingress.tls.secretName }}
      hosts:
        {{- range $redirect := .Values.redirector.redirects }}
        - {{ $redirect.host.from }}
        {{- end }}
{{- end }}
