{{- if .Values.redirector.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: redirector
  labels:
    app: redirector
    component: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: redirector
    component: nginx
{{- end }}
