{
 "title": "Service Level Objectives",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Success Rates (6h lookback window)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100* (sum(delta(binderhub_launch_time_seconds_count{status=\"success\"}[6h])) / sum(delta(binderhub_launch_time_seconds_count{status!=\"retry\"}[6h])))",
     "legendFormat": "Launches"
    },
    {
     "expr": "100 * sum(delta(binderhub_build_time_seconds_count{status=\"success\"}[6h])) / sum(delta(binderhub_build_time_seconds_count[6h]))",
     "legendFormat": "Builds"
    }
   ]
  },
  {
   "title": "Build/Launch Attempts (6h lookback window)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Launches" }
   ],
   "targets": [
    {
     "expr": "sum(delta(binderhub_launch_time_seconds_count[6h]))",
     "legendFormat": "Launches"
    },
    {
     "expr": "sum(delta(binderhub_build_time_seconds_count[6h]))",
     "legendFormat": "Builds"
    }
   ]
  },
  {
   "title": "Build/Launch Attempts (daily)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Launches" }
   ],
   "targets": [
    {
     "expr": "sum(delta(binderhub_launch_time_seconds_count[24h]))",
     "legendFormat": "Launches"
    },
    {
     "expr": "sum(delta(binderhub_build_time_seconds_count[24h]))",
     "legendFormat": "Builds"
    }
   ]
  }
 ]
}