{{- if .Values.analyticsPublisher.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: analytics-publisher
  labels:
    app: analytics-publisher
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  analytics-publisher.json: {{ toJson .Values.analyticsPublisher | quote }}
{{- end }}
