{{- if .Values.proxyPatches.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
{{- /* k8s 1.21+ required */ -}}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: proxy-patches
  labels:
    app: proxy-patches
    component: proxy-patches
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: proxy-patches
      release: {{ .Release.Name }}
{{- end }}
