# yamllint can be installed via `pip install yamllint`, and is used to verify
# that the YAML files in this repo seems valid.
#
#   yamllint --config-data=scripts/yamllint-config.yaml .
#
# We rely on the "relaxed" base configuration where indentation, line length,
# extra spaces, blank lines are raised as warnings - not errors. See
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration.
#
extends: relaxed

# Ignore any Helm chart templates as they are not pure YAML files.
#
# NOTE: If you make a change here, also update scripts/yamllint-no-secrets.yaml
#       as that overrides this by appending secrets/** as well.
#
ignore: |
  .git/**
  **/templates/**

# Ignore common warnings we don't want to bother with
rules:
  line-length: disable
  trailing-spaces: disable
  new-line-at-end-of-file: disable
