{{- if .Values.matomo.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matomo
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    {{- range $host := .Values.matomo.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /matomo
            pathType: Prefix
            backend:
              service:
                name: matomo
                port:
                  number: 9000
    {{- end }}
  tls:
    - secretName: kubelego-tls-matomo
      hosts:
        {{- range $host := .Values.matomo.ingress.hosts }}
        - {{ $host }}
        {{- end }}
{{- end }}
