{{- if .Values.matomo.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: matomo-nginx-config
data:
  redirects.conf: |
    server {
      listen 9000 default_server;

      root /var/www/html;

      location /matomo {
        rewrite ^/matomo/(.*)$ /$1 break;
        
        proxy_set_header X-Forwarded-Uri /matomo;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Host $host;

        proxy_pass http://127.0.0.1:80;
      }
    }
{{- end }}
