{{- if .Values.matomo.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
{{- /* k8s 1.21+ required */ -}}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: matomo
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  # Use 1.0 rather than 1, since `gt` only works with floats
  {{ if gt .Values.matomo.replicas 1.0 }}
  minAvailable: 1
  {{ else }}
  minAvailable: 0
  {{ end }}
  selector:
    matchLabels:
      app: matomo
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
{{- end }}
