{{- if .Values.matomo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: matomo
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.matomo.service.type }}
  selector:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  ports:
    - name: matomo
      protocol: TCP
      port: 9000
{{- end }}
